pipeline {
    agent any
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    // Navigate to the e2e folder and run npm ci
                    dir('e2e') {
                        bat 'npm ci'
                    }
                }
            }
        }

        stage('Run Production Tests') {
            steps {
                script {
                    // Change the directory to 'e2e' before running the batch file
                    dir('e2e') {
                        bat '.\\run_tests.bat production dev'
                    }
                }
            }
        }

        stage('Generate Reports') {
            steps {
                script {
                    echo "Generating reports..."
                }
                bat 'npm run postcucumber'
            }
        }

        stage('Archive Results') {
            steps {
                script {
                    echo "Archiving reports..."
                }
                archiveArtifacts artifacts: 'reports/**/*', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            script {
                echo "Pipeline finished"
            }
        }
        success {
            script {
                echo "Tests executed successfully!"
            }
        }
        failure {
            script {
                echo "Tests failed! Check logs and reports for details."
            }
        }
    }
}
