pipeline {
    agent any

    environment {
        COMMON_CONFIG_FILE = "env/common.env"
        NODE_ENV = "production"
    }

    stages {
        stage('Setup') {
            steps {
                script {
                    echo 'Setting up environment...'
                    // Change directory to the e2e folder
                    dir('e2e') {
                        bat 'npm ci' // Install dependencies in the e2e folder
                    }
                }
            }
        }

        stage('Run Production Tests') {
            steps {
                script {
                    echo 'Running production tests with @dev tag...'
                }
                bat 'npm run cucumber:production -- --tags @dev'
            }
        }

        stage('Generate Reports') {
            steps {
                script {
                    echo "Generating reports..."
                }
                bat 'npm run postcucumber'
            }
        }

        stage('Archive Results') {
            steps {
                script {
                    echo "Archiving reports..."
                }
                archiveArtifacts artifacts: 'reports/**/*', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            script {
                echo "Pipeline finished"
            }
        }
        success {
            script {
                echo "Tests executed successfully!"
            }
        }
        failure {
            script {
                echo "Tests failed! Check logs and reports for details."
            }
        }
    }
}
